"""add description and owner_id to teams

Revision ID: 2dfb270fa6fa
Revises: 27fbb1a055f7
Create Date: 2026-06-21 15:35:51.377932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfb270fa6fa'
down_revision: Union[str, Sequence[str], None] = '27fbb1a055f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'teams',
        sa.Column('description', sa.Text(), nullable=True)
    )

    op.add_column(
        'teams',
        sa.Column('owner_id', sa.Integer(), nullable=True)
    )

    # llenar datos existentes 
    op.execute("""
    UPDATE teams
    SET owner_id = (SELECT id FROM users LIMIT 1)
     """)

    # 🔥 ahora sí hacerlo obligatorio
    op.alter_column('teams', 'owner_id', nullable=False)

    op.create_foreign_key(
    "fk_teams_owner",
    "teams",
    "users",
    ["owner_id"],
    ["id"],
    ondelete="CASCADE"
)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'owner_id')
    op.drop_column('teams', 'description')
    # ### end Alembic commands ###
