"""add status, priority, due_date to tasks

Revision ID: 4c03bc1600fa
Revises: 60d6b26b8f6d
Create Date: 2026-06-17 20:05:02.683225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c03bc1600fa'
down_revision: Union[str, Sequence[str], None] = '60d6b26b8f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
